"""Cookie loading and first-run setup.

Discovery order for the default 'env' source:
  1. process environment (X_AUTH_TOKEN + X_CT0 already exported)
  2. ./.env in the current working directory  (dev / clone scenario)
  3. $XDG_CONFIG_HOME/xbook/.env             (system-wide installs)

If none are present and stdin is a TTY, the interactive setup wizard runs.
"""

import getpass
import os
import shutil
import sqlite3
import sys
import tempfile
from glob import glob
from pathlib import Path

from .errors import MissingCookies


def _playwright_cookies(auth_token: str, ct0: str) -> list[dict]:
    """Build the cookie list Playwright expects."""
    cookies = []
    for domain in (".x.com", ".twitter.com"):
        cookies.append({"name": "auth_token", "value": auth_token, "domain": domain,
                        "path": "/", "httpOnly": True, "secure": True, "sameSite": "Lax"})
        cookies.append({"name": "ct0", "value": ct0, "domain": domain,
                        "path": "/", "httpOnly": False, "secure": True, "sameSite": "Lax"})
    return cookies


# --- Discovery ---------------------------------------------------------------

def user_config_path() -> Path:
    raw = os.environ.get("XDG_CONFIG_HOME")
    base = Path(raw) if raw else Path.home() / ".config"
    return base / "xbook" / ".env"


def _parse_env_file(path: Path) -> tuple[str | None, str | None]:
    """Extract X_AUTH_TOKEN and X_CT0 from a .env file. Doesn't pollute os.environ."""
    auth = ct0 = None
    try:
        contents = path.read_text()
    except OSError:
        return None, None
    for line in contents.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key == "X_AUTH_TOKEN":
            auth = value or None
        elif key == "X_CT0":
            ct0 = value or None
    return auth, ct0


def _discover_credentials() -> tuple[str, str] | None:
    """First source with both auth_token and ct0 wins. Returns None if nothing found."""
    auth = os.environ.get("X_AUTH_TOKEN")
    ct0 = os.environ.get("X_CT0")
    if auth and ct0:
        return auth, ct0

    for path in (Path.cwd() / ".env", user_config_path()):
        if path.exists():
            a, c = _parse_env_file(path)
            if a and c:
                return a, c
    return None


# --- Persistence -------------------------------------------------------------

def save_env_file(path: Path, auth_token: str, ct0: str) -> None:
    """Write an .env file with chmod 600."""
    path.parent.mkdir(parents=True, exist_ok=True)
    contents = (
        "# Generated by `xbook --setup` — these cookies are equivalent to a\n"
        "# logged-in X session. Treat them like a password. Never commit.\n"
        f"X_AUTH_TOKEN={auth_token}\n"
        f"X_CT0={ct0}\n"
    )
    path.write_text(contents)
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


# --- Firefox reader ----------------------------------------------------------

def read_from_firefox(profile: str | None = None) -> tuple[str, str]:
    """Read auth_token and ct0 from Firefox's cookies.sqlite.

    The DB is locked while Firefox is running, so we copy it to a temp file first.
    Returns (auth_token, ct0). Raises MissingCookies if not found.
    """
    base = Path.home() / ".mozilla" / "firefox"
    if profile:
        candidates = [base / profile / "cookies.sqlite"]
    else:
        candidates = [Path(p) for p in glob(str(base / "*" / "cookies.sqlite"))]
    if not candidates:
        raise MissingCookies(
            f"No Firefox profile with cookies.sqlite found under {base}. "
            "Is Firefox installed?"
        )

    for db_path in candidates:
        if not db_path.exists():
            continue
        with tempfile.NamedTemporaryFile(suffix=".sqlite", delete=False) as tmp:
            shutil.copy2(db_path, tmp.name)
            tmp_path = tmp.name
        try:
            conn = sqlite3.connect(tmp_path)
            rows = conn.execute(
                "SELECT name, value FROM moz_cookies "
                "WHERE host IN ('.x.com', 'x.com', '.twitter.com', 'twitter.com') "
                "  AND name IN ('auth_token', 'ct0')"
            ).fetchall()
            conn.close()
        finally:
            os.unlink(tmp_path)

        found = {name: value for name, value in rows}
        if "auth_token" in found and "ct0" in found:
            return found["auth_token"], found["ct0"]

    raise MissingCookies(
        "auth_token and ct0 not found in any Firefox profile. "
        "Make sure you are logged in to x.com in Firefox."
    )


# --- Interactive setup wizard ------------------------------------------------

WIZARD_INTRO = """\
xbook needs your X session cookies (auth_token, ct0) to read your bookmarks.
These are equivalent to a logged-in session — xbook stores them locally with
chmod 600 and never transmits them anywhere except x.com itself.

How would you like to provide them?
  1) Read from Firefox (you must be logged in to x.com in Firefox)
  2) Paste them manually (DevTools -> Application -> Cookies -> x.com)
  3) Cancel — show me the docs
"""


def _prompt_choice() -> str:
    """Get a 1/2/3 choice. Re-prompts on invalid input."""
    while True:
        choice = input("> ").strip()
        if choice in ("1", "2", "3"):
            return choice
        print("Please enter 1, 2, or 3.")


def _manual_paste() -> tuple[str, str]:
    print()
    print("Open x.com in your browser, logged in.")
    print("DevTools -> Application -> Cookies -> https://x.com")
    print("(Values are hidden as you paste.)")
    print()
    auth = getpass.getpass("auth_token: ").strip()
    ct0 = getpass.getpass("ct0: ").strip()
    if not auth or not ct0:
        raise MissingCookies("auth_token and ct0 cannot be empty.")
    return auth, ct0


def setup_wizard(save_path: Path | None = None) -> tuple[str, str]:
    """Interactive setup. Returns (auth, ct0) and persists them if user agrees.

    `save_path` defaults to $XDG_CONFIG_HOME/xbook/.env.
    Raises MissingCookies if the user cancels or supplies empty values.
    """
    if not sys.stdin.isatty():
        raise MissingCookies(
            "no cookies found and stdin is not a TTY; cannot run interactive setup. "
            "Set X_AUTH_TOKEN and X_CT0 in your environment or in .env, "
            "or run `xbook --setup` in an interactive terminal."
        )

    save_path = save_path or user_config_path()

    print(WIZARD_INTRO)
    choice = _prompt_choice()

    if choice == "3":
        raise MissingCookies(
            "setup cancelled. See README.md for how to extract cookies manually."
        )

    auth = ct0 = None

    if choice == "1":
        print()
        print("Reading cookies from Firefox...")
        try:
            auth, ct0 = read_from_firefox()
            print("✓ Found cookies in Firefox.")
        except MissingCookies as e:
            print(f"✗ {e}")
            print()
            print("Falling back to manual entry.")
            auth, ct0 = _manual_paste()

    if choice == "2":
        auth, ct0 = _manual_paste()

    print()
    answer = input(f"Save to {save_path}? [Y/n] ").strip().lower()
    if answer in ("", "y", "yes"):
        save_env_file(save_path, auth, ct0)
        print(f"✓ Saved (chmod 600).")
    else:
        print("OK — not saving. Cookies will only be used for this run.")

    return auth, ct0


# --- Public API used by the CLI ---------------------------------------------

def load(source: str = "env", *, allow_setup: bool = True) -> list[dict]:
    """Resolve cookies and return them as a Playwright cookie list.

    source='env'     — check process env, then ./.env, then ~/.config/xbook/.env.
                       Falls back to the setup wizard if interactive and `allow_setup`.
    source='firefox' — read directly from the Firefox cookie store. No wizard fallback.
    """
    if source == "firefox":
        auth, ct0 = read_from_firefox()
        return _playwright_cookies(auth, ct0)

    if source != "env":
        raise ValueError(f"unknown cookie source: {source!r}")

    creds = _discover_credentials()
    if creds is None:
        if not allow_setup:
            raise MissingCookies(
                "X_AUTH_TOKEN and X_CT0 not found in environment, ./.env, "
                f"or {user_config_path()}. Run `xbook --setup` to configure."
            )
        creds = setup_wizard()

    auth, ct0 = creds
    return _playwright_cookies(auth, ct0)
